@echo off

rem Installieren der benötigte Python-Bibliotheken
echo Installing tkinter...
py -m pip install tkinter
echo Installing customtkinter...
py -m pip install customtkinter
echo Installing numpy...
py -m pip install numpy
echo Installing json...
py -m pip install json
echo Installing os...
py -m pip install os
echo Installing math...
py -m pip install math
echo Installing datetime...
py -m pip install datetime
echo Installing matplotlib.pyplot...
py -m pip install matplotlib.pyplot
echo Installing matplotlib...
py -m pip install matplotlib

echo Installation abgeschlossen!
pause
